steps:
  # Build the container image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_BINARY_NAME'
      - '--allow-unauthenticated'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      -  '--set-env-vars'
      - "DB_ADDRESS=${_DB_ADDRESS}"
      -  '--set-env-vars'
      - "DB_PORT=${_DB_PORT}"
      -  '--set-env-vars'
      - "DB_DATABASE=${_DB_DATABASE}"
      -  '--set-env-vars'
      - "DB_USERNAME=${_DB_USERNAME}"
      -  '--set-env-vars'
      - "DB_PASSWORD=${_DB_PASSWORD}"
images:
  - 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA'