steps:
  # Build the container image.
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA'
    - '--build-arg'
    - "DB_ADDRESS=${_DB_ADDRESS}"
    - '--build-arg'
    - "DB_PORT=${_DB_PORT}"
    - '--build-arg'
    - "DB_DATABASE=${_DB_DATABASE}"
    - '--build-arg'
    - "DB_USERNAME=${_DB_USERNAME}"
    - '--build-arg'
    - "DB_PASSWORD=${_DB_PASSWORD}"
    - '.'
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_BINARY_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
images:
  - 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA'